### ISSUE TITLE
能不能增加一个 单独设置过期时间的函数？

### ISSUE THREAD

**Issue by jasonhe88** [happyfish100/libshmcache#13]
比如

boolean ShmCache::setTtl(string $key, long $ttl)

谢谢这么好的东西，找好久了

**Comment by happyfish100** [comment]
什么场景下需要更改key的ttl呢？

**Comment by jasonhe88** [comment]
自己的业务场景吧，目前是用setValue把值重写一遍，加上更新的TTL

**Comment by happyfish100** [comment]
已经支持了。
boolean ShmCache::setTTL(string $key, long $ttl);
API详情参见README.md

**Comment by jasonhe88** [comment]
@happyfish100 多谢啦！！
