### ISSUE TITLE
FIFO vs LRU

### ISSUE THREAD

**Issue by jasonhe88** [happyfish100/libshmcache#19]
发现缓存策略是FIFO，有点好奇为什么没有采用LRU， 一般情况下LRU的性能应该比FIFO好一些。

是有什么特别的考虑吗？谢谢！

**Comment by happyfish100** [comment]
主要是因为FIFO实现很简单，对于单一应用（或特定应用场景）来讲，FIFO淘汰算法效果是接近LRU的。

**Comment by jasonhe88** [comment]
明白了，感谢！！
