### ISSUE TITLE
关于读操作无锁的疑问

### ISSUE THREAD

**Issue by samsonwang** [happyfish100/libshmcache#20]
你好，我在发现，对于读操作，在`shm_ht_get`函数中直接将共享内存中的地址保存在`value->data`中，也就意味着获取value的时候返回的是共享内存地址。
如果对同一个key进行并发读写，会不会出现对同一块内存操作冲突引起数据错误呢？

**Comment by happyfish100** [comment]
如果回收了在有效期内的key对应的value空间，在释放原有空间前会休眠一小段时间。
对应的配置项如下：
# sleep time to avoid other processes read dirty data when
# recycle more than one valid (in TTL / not expired) KV entries
# 0 for never sleep
# unit: microsecond (us)
# default: 0
value_policy.sleep_us_when_recycle_valid_entries = 1000

**Comment by samsonwang** [comment]
嗯，明白了，如果对于数据正确性比较敏感的场景，在读操作上还是加锁比较好的。
